// client/src/components/Achievements.tsx
import { faTrophy } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import type React from "react";
import GameAnalysis from "../avalon-analysis.ts";
import styles from "./Achievements.module.css";

interface Badge {
	title: string;
	body: string;
}

interface Mission {
	state: string;
	team: string[];
	proposals: any[];
	evilOnTeam?: string[];
	failsRequired: number;
	numFails: number;
}

interface OutcomeRole {
	name: string;
	role: string;
}

interface GameOutcome {
	state: string;
	roles: OutcomeRole[];
	assassinated?: string;
}

interface Game {
	players: string[];
	missions: Mission[];
	outcome: GameOutcome;
}

interface RoleInfo {
	team: string;
}

interface Config {
	roleMap: Record<string, RoleInfo>;
}

interface Lobby {
	game: Game;
}

interface AvalonProps {
	lobby: Lobby;
	config: Config;
}

interface AchievementsProps {
	avalon: AvalonProps;
}

const Achievements: React.FC<AchievementsProps> = ({ avalon }) => {
	const getBadges = (): Badge[] => {
		if (avalon.lobby.game.outcome.state === "CANCELED") return [];

		const gameAnalysis = new GameAnalysis(
			avalon.lobby.game,
			avalon.config.roleMap,
		);
		return gameAnalysis.getBadges();
	};

	const badges = getBadges();

	if (!badges.length) {
		return null;
	}

	return (
		<div className={styles.container}>
			<div className={styles.title}>Achievements</div>
			{badges.map((badge) => (
				<div key={badge.title} className={styles.badgeContainer}>
					<div className={styles.card}>
						<div className={styles.cardTitle}>
							<FontAwesomeIcon
								icon={faTrophy}
								className={styles.trophyIcon}
								color="yellow"
							/>
							<div className={styles.badgeTitle}>{badge.title}</div>
						</div>
						<div className={styles.cardText}>{badge.body}</div>
					</div>
				</div>
			))}
		</div>
	);
};

export default Achievements;

// client/src/components/Achievements.vue
<template>
  <div v-if="badges.length" class='pt-6'>
    <div class='text-h4' style='text-align: center;'>Achievements</div>
    <div v-for="badge in badges" :key="badge.title" class="pt-2">
    <v-card class="blue-grey lighten-4" min-width='400' max-width='900'>
      <v-card-title class="cyan lighten-2">
        <v-icon left color="yellow">fas fa-trophy</v-icon>
        <div class='text-h6'>{{ badge.title }}</div></v-card-title>
      <v-card-text>{{ badge.body }}</v-card-text>
    </v-card>
    </div>
  </div>
</template>
<script>
import GameAnalysis from "@/avalon-analysis.js";

export default {
  name: "Achievements",
  props: ["avalon"],
  computed: {
    badges() {
      if (this.avalon.lobby.game.outcome.state == 'CANCELED') return [];
      const gameAnalysis = new GameAnalysis(
        this.avalon.lobby.game,
        this.avalon.config.roleMap
      );
      return gameAnalysis.getBadges();
    }
  }
};
</script>
<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>
