// client/src/components/Login.tsx
import React, { useState, useEffect, useRef } from 'react';
import StatsDisplay from './StatsDisplay';
import styles from './Login.module.css';

interface AvalonUser {
  name: string;
  email: string;
  stats: {
    games?: number;
    good?: number;
    wins?: number;
    good_wins?: number;
    playtimeSeconds?: number;
  };
}

interface GlobalStats {
  games: number;
  good_wins: number;
}

interface AvalonApi {
  user?: AvalonUser;
  globalStats?: GlobalStats;
  createLobby: (name: string) => Promise<void>;
  joinLobby: (name: string, lobby: string) => Promise<void>;
}

interface LoginProps {
  avalon: AvalonApi;
}

const Login: React.FC<LoginProps> = ({ avalon }) => {
  const [name, setName] = useState<string>(avalon.user ? avalon.user.name : '');
  const [lobby, setLobby] = useState<string>('');
  const [errorMessage, setErrorMessage] = useState<string>('');
  const [showLobbyInput, setShowLobbyInput] = useState<boolean>(false);
  const [isJoiningLobby, setIsJoiningLobby] = useState<boolean>(false);
  const [isCreatingLobby, setIsCreatingLobby] = useState<boolean>(false);
  const [alertTimeoutTimer, setAlertTimeoutTimer] = useState<NodeJS.Timeout | null>(null);
  
  const nameTextFieldRef = useRef<HTMLInputElement>(null);
  const lobbyTextFieldRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    setInputWidth(nameTextFieldRef);
    document.title = 'Avalon - ' + (name ? name : avalon.user?.email || '');
  }, [name, avalon.user?.email]);

  useEffect(() => {
    const textFieldRef = showLobbyInput ? lobbyTextFieldRef : nameTextFieldRef;
    if (textFieldRef.current) {
      textFieldRef.current.focus();
      setInputWidth(textFieldRef);
    }
  }, [showLobbyInput]);

  const setInputWidth = (fieldRef: React.RefObject<HTMLInputElement>) => {
    const size = 20;
    if (fieldRef.current) {
      fieldRef.current.setAttribute('size', size.toString());
    }
  };

  const genericLogin = (loadingStateSetter: React.Dispatch<React.SetStateAction<boolean>>, loginPromise: Promise<void>) => {
    loadingStateSetter(true);
    loginPromise
      .catch((err: Error) => showErrorMessage(err.message))
      .finally(() => loadingStateSetter(false));
  };

  const createLobby = () => {
    genericLogin(setIsCreatingLobby, avalon.createLobby(name));
  };

  const joinLobby = () => {
    genericLogin(setIsJoiningLobby, avalon.joinLobby(name, lobby));
  };

  const showErrorMessage = (errorMsg: string) => {
    if (alertTimeoutTimer) {
      clearTimeout(alertTimeoutTimer);
    }
    setErrorMessage(errorMsg);
    const timer = setTimeout(() => {
      setAlertTimeoutTimer(null);
      setErrorMessage('');
    }, 5000);
    setAlertTimeoutTimer(timer);
  };

  const handleNameChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setName(event.target.value.toUpperCase());
  };

  const handleLobbyChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setLobby(event.target.value.toUpperCase());
  };

  const handleLobbyKeyUp = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.key === 'Enter') {
      joinLobby();
    }
  };

  return (
    <div className={styles.container}>
      <div className={styles.layout}>
        {!showLobbyInput ? (
          <>
            <input
              ref={nameTextFieldRef}
              className={`${styles.textField} ${errorMessage ? styles.error : ''}`}
              placeholder="Your Name"
              value={name}
              onChange={handleNameChange}
              autoFocus
            />
            {errorMessage && <div className={styles.errorMessage}>{errorMessage}</div>}
            <button
              className={`${styles.button} ${isCreatingLobby ? styles.loading : ''}`}
              disabled={!name}
              onClick={createLobby}
            >
              {isCreatingLobby ? 'Creating...' : 'Create Lobby'}
            </button>
            <button
              className={styles.button}
              disabled={!name || isCreatingLobby}
              onClick={() => setShowLobbyInput(true)}
            >
              Join Lobby
            </button>
          </>
        ) : (
          <>
            <input
              ref={lobbyTextFieldRef}
              className={`${styles.textField} ${errorMessage ? styles.error : ''}`}
              placeholder="Lobby"
              value={lobby}
              onChange={handleLobbyChange}
              onKeyUp={handleLobbyKeyUp}
            />
            {errorMessage && <div className={styles.errorMessage}>{errorMessage}</div>}
            <button
              className={`${styles.button} ${isJoiningLobby ? styles.loading : ''}`}
              disabled={!lobby}
              onClick={joinLobby}
            >
              {isJoiningLobby ? 'Joining...' : 'Join Lobby'}
            </button>
            <button
              className={styles.button}
              disabled={isJoiningLobby}
              onClick={() => setShowLobbyInput(false)}
            >
              Cancel
            </button>
          </>
        )}
        <div className={styles.spacer}></div>
        <StatsDisplay 
          stats={avalon.user?.stats || {}} 
          globalStats={avalon.globalStats} 
        />
      </div>
    </div>
  );
};

export default Login;

// client/src/components/Login.vue
<template>
  <v-container justify-center class="cyan lighten-5">
    <v-layout align-center justify-center column fill-height>
    <template v-if='!showLobbyInput'>
      <v-text-field
        label="Your Name" @input="name = name.toUpperCase()" ref='nameTextField' v-model="name" :error-messages='errorMsg' autofocus>          
      </v-text-field>
      <v-btn
       :disabled='!name' @click='createLobby()' :loading="isCreatingLobby">
        Create Lobby
      </v-btn>
      <v-btn :disabled='!name || isCreatingLobby' @click='showLobbyInput = true'>
        Join Lobby
      </v-btn>
  </template>
   <template v-else>
    <v-text-field ref="lobbyTextField"  @input="lobby = lobby.toUpperCase()" label="Lobby" :error-messages='errorMsg' v-model="lobby" @keyup.native.enter="joinLobby()"></v-text-field>
    <v-btn :disabled='!lobby' @click='joinLobby()' :loading="isJoiningLobby">
      Join Lobby
    </v-btn>
    <v-btn @click='showLobbyInput = false' :disabled='isJoiningLobby'>
      Cancel
    </v-btn>
   </template>
  <div style='padding-top: 30px'></div>
  <StatsDisplay :stats='avalon.user.stats' :globalStats='avalon.globalStats'></StatsDisplay>
  </v-layout>
  </v-container>
</template>

<script>
import StatsDisplay from './StatsDisplay.vue'

export default {
  name: 'Login',
  components: {
    StatsDisplay
  },
  data() {
    return {
      name: this.avalon.user ? this.avalon.user.name : '',
      lobby: '',
      alertTimeoutTimer: null,
      errorMsg: '',
      showLobbyInput: false,
      isJoiningLobby: false,
      isCreatingLobby: false
    };
  },
  props: {
    avalon: Object
  },
  methods: {
    genericLogin(loadingValue, loginPromise) {
      this[loadingValue] = true;
      loginPromise.catch(
        (err) => this.showErrorMessage(err)).finally(
          () => this[loadingValue] = false);
    },
    createLobby() {
      this.genericLogin('isCreatingLobby', this.avalon.createLobby(this.name));
    },
    joinLobby() {
      this.genericLogin('isJoiningLobby', this.avalon.joinLobby(this.name, this.lobby));
    },
    showErrorMessage(errMsg) {
      const vm = this;
      if (vm.alertTimeoutTimer != null) {
        clearTimeout(vm.alertTimeoutTimer);
      }
      vm.errorMsg = errMsg.toString();
      this.alertTimeoutTimer = setTimeout(() => {
        vm.alertTimeoutTimer = null;
        vm.errorMsg = '';
      }, 5000);
    },
    setInputWidth(field) {
      const size = 20;
      this.$refs[field].$el.getElementsByTagName('input')[0].setAttribute('size', size);
    }
  },
  mounted: function() {
    this.setInputWidth('nameTextField');
    document.title = 'Avalon - ' + (this.name ? this.name : this.avalon.user.email);
  },
  watch: {
    showLobbyInput: function() {
      const vm = this;
      let textField = 'lobbyTextField';
      if (!this.showLobbyInput) {
        textField = 'nameTextField';
      }
      this.$nextTick(() => {
        vm.$refs[textField].$el.getElementsByTagName('input')[0].focus();
        vm.setInputWidth(textField);
      });
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>
