// client/src/components/MissionAction.tsx
import React, { useState, useMemo } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCheckCircle, faTimesCircle } from '@fortawesome/free-solid-svg-icons';
import styles from './MissionAction.module.css';

interface User {
  name: string;
}

interface Proposal {
  team: string[];
}

interface Mission {
  team: string[];
}

interface Game {
  currentProposal: Proposal;
  currentMission: Mission;
}

interface AvalonProps {
  user: User;
  game: Game;
  doMission: (vote: boolean) => void;
}

interface MissionActionProps {
  avalon: AvalonProps;
}

function joinWithAnd(array: string[]): string {
  if (array.length === 0) return '';
  if (array.length === 1) return array[0];
  const arrCopy = array.slice(0);
  const lastElement = arrCopy.pop();
  return arrCopy.join(', ') + ' and ' + lastElement;
}

const MissionAction: React.FC<MissionActionProps> = ({ avalon }) => {
  const [needsToVote, setNeedsToVote] = useState(
    avalon.game.currentProposal?.team?.includes(avalon.user?.name) || false
  );

  const stillWaitingFor = useMemo(() => {
    return (avalon.game.currentProposal?.team || [])
      .filter(name => !(avalon.game.currentMission?.team || []).includes(name))
      .filter(name => name !== avalon.user?.name);
  }, [avalon.game.currentProposal?.team, avalon.game.currentMission?.team, avalon.user?.name]);

  const waitingForText = useMemo(() => {
    if (stillWaitingFor.length > 0) {
      return 'Waiting for ' + joinWithAnd(stillWaitingFor);
    } else {
      return 'Waiting for results...';
    }
  }, [stillWaitingFor]);

  const missionVote = (vote: boolean) => {
    setNeedsToVote(false);
    avalon.doMission(vote);
  };

  return (
    <div className={styles.card}>
      <div className={styles.cardTitle}>
        Mission in Progress
      </div>
      <div className={styles.cardContent}>
        {needsToVote ? (
          <div className={styles.buttonLayout}>
            <button
              className={styles.successButton}
              onClick={() => missionVote(true)}
            >
              <FontAwesomeIcon icon={faCheckCircle} className={styles.successIcon} />
              SUCCESS
            </button>
            <button
              className={styles.failButton}
              onClick={() => missionVote(false)}
            >
              <FontAwesomeIcon icon={faTimesCircle} className={styles.failIcon} />
              FAIL
            </button>
          </div>
        ) : (
          <div>{waitingForText}</div>
        )}
      </div>
    </div>
  );
};

export default MissionAction;

// client/src/components/MissionAction.vue
<template>
  <v-card class="blue-grey lighten-4">
    <v-card-title class="light-blue lighten-4">
      Mission in Progress
     </v-card-title>
     <v-card-text>
      <div v-if='needsToVote'>
        <v-layout align-center justify-space-between fill-height>
        <v-btn @click='missionVote(true)'>
            <v-icon left color="green">fas fa-check-circle</v-icon>
                SUCCESS
            </v-btn>
        <v-btn @click='missionVote(false)'>
          <v-icon left color="red">fas fa-times-circle</v-icon>
            FAIL
        </v-btn>
        </v-layout>
       </div>
       <div v-else>
           <!-- need to make a more dramatic reveal at the end! -->
           {{ waitingForText }}
       </div>
     </v-card-text>
  </v-card>
</template>

<script>
import _ from 'lodash';

export default {
  name: 'MissionAction',
  props: [ 'avalon' ],
  data() {
      return {        
          needsToVote: this.avalon.game.currentProposal.team.includes(this.avalon.user.name)
      };
  },
  methods: {
      missionVote(vote) {
        // no loading state, we want to hide the results as fast as possible
        this.needsToVote = false;
        this.avalon.doMission(vote);
      }
  },
  computed: {
    stillWaitingFor() {
      return _.difference(this.avalon.game.currentProposal.team,
                          this.avalon.game.currentMission.team).filter(
                            n => n != this.avalon.user.name);
    },
    waitingForText() {
      if (this.stillWaitingFor.length > 0) {
        return 'Waiting for ' + this.stillWaitingFor.joinWithAnd();
      } else {
        return 'Waiting for results...';
      }
    }
  }
}
</script>
<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>
