// client/src/components/ProposalsCounter.vue
<template>
<v-container>
  <v-layout align-center justify-space-around>
    <div v-for="n in 5" :key="n">
      <v-icon v-if='avalon.game.currentProposalIdx + 1 == n' class="fas fa-crown"></v-icon>
      <v-icon v-else small class="fas fa-circle"></v-icon>
    </div>
</v-layout>
</v-container>
</template>

<script>
export default {
  name: 'ProposalCounter',
  props: [ 'avalon' ],
}
</script>
<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>

// client/src/components/ProposalsCounter.tsx
import React from 'react';
import styles from './ProposalsCounter.module.css';

interface Game {
  currentProposalIdx: number;
}

interface AvalonProps {
  game: Game;
}

interface ProposalsCounterProps {
  avalon: AvalonProps;
}

const ProposalsCounter: React.FC<ProposalsCounterProps> = ({ avalon }) => {
  return (
    <div className={styles.container}>
      <div className={styles.layout}>
        {[1, 2, 3, 4, 5].map((n) => (
          <div key={n} className={styles.proposalIcon}>
            {avalon.game.currentProposalIdx + 1 === n ? (
              <span className={styles.crown}>👑</span>
            ) : (
              <span className={styles.circle}>●</span>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};

export default ProposalsCounter;
