// client/src/components/TeamVoteAction.tsx
import React, { useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faVoteYea } from '@fortawesome/free-solid-svg-icons';
import { faThumbsUp, faThumbsDown } from '@fortawesome/free-regular-svg-icons';
import styles from './TeamVoteAction.module.css';

function joinWithAnd(array: string[]): string {
  if (array.length === 0) return '';
  if (array.length === 1) return array[0];
  const arrCopy = array.slice(0);
  const lastElement = arrCopy.pop();
  return arrCopy.join(', ') + ' and ' + lastElement;
}

interface User {
  name: string;
}

interface Proposal {
  team: string[];
  votes: string[];
}

interface Game {
  currentProposalIdx: number;
  currentProposal: Proposal;
  currentProposer: string;
}

interface AvalonProps {
  game: Game;
  user: User;
  voteTeam: (vote: boolean) => Promise<void>;
}

interface TeamVoteActionProps {
  avalon: AvalonProps;
}

const TeamVoteAction: React.FC<TeamVoteActionProps> = ({ avalon }) => {
  const hasVoted = avalon.game.currentProposal?.votes?.includes(avalon.user?.name) || false;

  const [loadingState, setLoadingState] = useState({ yes: false, no: false });
  const [disabledState, setDisabledState] = useState({ yes: hasVoted, no: hasVoted });
  const [votedState, setVotedState] = useState({ yes: false, no: false });

  const proposer = avalon.game.currentProposer === avalon.user?.name
    ? 'your'
    : avalon.game.currentProposer + "'s ";

  const teamVote = (vote: boolean) => {
    const myState = vote ? 'yes' : 'no';
    const otherState = vote ? 'no' : 'yes';

    setLoadingState(prev => ({ ...prev, [myState]: true }));
    setDisabledState(prev => ({ ...prev, [otherState]: true }));

    avalon.voteTeam(vote).finally(() => {
      setLoadingState(prev => ({ ...prev, [myState]: false }));
      setDisabledState(prev => ({
        ...prev,
        [myState]: true,
        [otherState]: false
      }));
      setVotedState({
        [myState]: true,
        [otherState]: false
      } as { yes: boolean; no: boolean });
    });
  };

  return (
    <div className={styles.card}>
      <div className={styles.cardTitle}>
        Team Proposal Vote ({avalon.game.currentProposalIdx + 1}/5)
      </div>
      <div className={styles.cardContent}>
        <div className={styles.votingText}>
          Voting for {proposer} team of {joinWithAnd(avalon.game.currentProposal?.team || [])}
        </div>
        <div className={styles.buttonLayout}>
          <button
            className={`${styles.button} ${styles.approveButton} ${loadingState.yes ? styles.loading : ''}`}
            onClick={() => teamVote(true)}
            disabled={disabledState.yes}
          >
            <FontAwesomeIcon
              icon={votedState.yes ? faVoteYea : faThumbsUp}
              className={`${styles.icon} ${votedState.yes ? styles.greenIcon : styles.greenIcon}`}
            />
            Approve
          </button>
          <button
            className={`${styles.button} ${styles.rejectButton} ${loadingState.no ? styles.loading : ''}`}
            onClick={() => teamVote(false)}
            disabled={disabledState.no}
          >
            <FontAwesomeIcon
              icon={votedState.no ? faVoteYea : faThumbsDown}
              className={`${styles.icon} ${votedState.no ? styles.redIcon : styles.redIcon}`}
            />
            Reject
          </button>
        </div>
      </div>
    </div>
  );
};

export default TeamVoteAction;

// client/src/components/TeamVoteAction.vue
<template>
    <v-card class="blue-grey lighten-4">
      <v-card-title class="light-blue lighten-4">
          Team Proposal Vote ({{ this.avalon.game.currentProposalIdx + 1 }}/5)
      </v-card-title>
      <v-card-text>
        <div>Voting for {{ proposer }} team of {{ this.avalon.game.currentProposal.team.joinWithAnd() }}</div>
        <v-layout align-center justify-space-between fill-height>
        <v-btn @click='teamVote(true)'
         v-bind:loading='loadingState.yes'
         v-bind:disabled='disabledState.yes'>
            <v-icon v-if='votedState.yes' left color='green'>fas fa-vote-yea</v-icon>
            <v-icon v-else left color="green">far fa-thumbs-up</v-icon>
            Approve
        </v-btn>
        <v-btn @click='teamVote(false)'
         v-bind:loading='loadingState.no'
         v-bind:disabled='disabledState.no'>
          <v-icon v-if='votedState.no' left color='red'>fas fa-vote-yea</v-icon>
          <v-icon v-else left color="red">far fa-thumbs-down</v-icon>
            Reject
        </v-btn>
        </v-layout>
    </v-card-text>
    </v-card>
</template>

<script>
export default {
  name: 'TeamVoteAction',
  props: [ 'avalon' ],
  data() {
      const hasVoted = this.avalon.game.currentProposal.votes.includes(this.avalon.user.name);
      return {
          // TODO: can use simple array as long as you use Vue.set (not direct assignment)
          // see: https://vuejs.org/v2/guide/list.html#Caveats
          loadingState: { yes: false, no: false } ,
          disabledState: { yes: hasVoted, no: hasVoted },
          votedState: { yes: false, no: false }          
      };
  },
  computed: {
      proposer() {
          return (this.avalon.game.currentProposer == this.avalon.user.name) ?
            'your' : this.avalon.game.currentProposer + "'s ";
      },
  },
  methods: {
      teamVote(vote) {
          const myState = vote ? 'yes' : 'no';
          const otherState = vote ? 'no' : 'yes';
          this.loadingState[myState] = true;
          this.disabledState[otherState] = true;
          this.avalon.voteTeam(vote).finally(() => {
              this.loadingState[myState] = false;
              this.disabledState[myState] = true;
              this.disabledState[otherState] = false;
              this.votedState[myState] = true;
              this.votedState[otherState] = false;
          });
      }
  }
}
</script>
<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>
