// client/src/components/ToolbarQuitButton.tsx
import React, { useState } from 'react';
import styles from './ToolbarQuitButton.module.css';

interface AvalonApi {
  isGameInProgress: boolean;
  cancelGame: () => Promise<void>;
  leaveLobby: () => void;
}

interface ToolbarQuitButtonProps {
  avalon: AvalonApi;
}

const ToolbarQuitButton: React.FC<ToolbarQuitButtonProps> = ({ avalon }) => {
  const [quitting, setQuitting] = useState(false);
  const [dialog, setDialog] = useState(false);

  const actionDescription = avalon.isGameInProgress ? 'Cancel Game' : 'Leave Lobby';
  const gameInProgressText = avalon.isGameInProgress ? 'The current game will be canceled!' : '';

  const quitButtonClicked = () => {
    setQuitting(true);
    setDialog(false);

    if (avalon.isGameInProgress) {
      avalon.cancelGame().finally(() => setQuitting(false));
    } else {
      avalon.leaveLobby();
    }
  };

  return (
    <>
      <button
        className={`${styles.quitButton} ${quitting ? styles.loading : ''}`}
        onClick={() => setDialog(true)}
        disabled={quitting}
      >
        <span className={styles.icon}>🚪</span>
        Quit
      </button>

      {dialog && (
        <div className={styles.overlay} onClick={() => setDialog(false)}>
          <div className={styles.dialog} onClick={(e) => e.stopPropagation()}>
            <div className={styles.card}>
              <div className={styles.title}>
                <h3>{actionDescription}?</h3>
              </div>
              <div className={styles.content}>
                {gameInProgressText && <p>{gameInProgressText}</p>}
                <p>Are you sure you want to proceed?</p>
              </div>
              <div className={styles.divider}></div>
              <div className={styles.actions}>
                <button onClick={quitButtonClicked} className={styles.primaryButton}>
                  {actionDescription}
                </button>
                <button onClick={() => setDialog(false)} className={styles.secondaryButton}>
                  Nevermind
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
};

export default ToolbarQuitButton;

// client/src/components/ToolbarQuitButton.vue
<template>
  <v-dialog v-model="dialog" max-width='450'>
    <template v-slot:activator="{ on }">
        <v-btn v-on="on" light :loading='quitting'>
        <v-icon left>exit_to_app</v-icon>
        Quit
        </v-btn>
    </template>
    <v-card class="cyan lighten-4">
      <v-card-title class="cyan lighten-2">
          <h3>{{ actionDescription }}?</h3>
      </v-card-title>
      <v-card-text>
          {{ gameInProgressText }}
          Are you sure you want to proceed?
      </v-card-text>
      <v-divider></v-divider>
      <v-card-actions>
        <v-spacer></v-spacer>
        <v-btn color="primary" @click='quitButtonClicked()'>
            {{ actionDescription }}
        </v-btn>
        <v-btn color="secondary" @click='dialog = false'>
            Nevermind
        </v-btn>        
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script>
export default {
  name: 'ToolbarQuitButton',
  props: [ 'avalon' ],
  data() {
      return {
          quitting: false,
          dialog: false
      };
  },
  computed: {
      actionDescription() {
        if (this.avalon.isGameInProgress) {
            return 'Cancel Game';
        }
        return 'Leave Lobby';
      },
      gameInProgressText() {
          if (this.avalon.isGameInProgress) {
              return 'The current game will be canceled!'
          } else {
              return '';
          }
      }
  },
  methods: {
      quitButtonClicked() {
          this.quitting = true;
          this.dialog = false;
          if (this.avalon.isGameInProgress) {
              this.avalon.cancelGame().finally(() => this.quitting = false);
          } else {
              this.avalon.leaveLobby();
          }
      }
  }
}
</script>
<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>
